version: '3'

services:
  db:
    image: mysql
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: User
      MYSQL_PASSWORD: 123456789

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html

volumes:
  db_data: