version: '3'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway/gateway-main/server.log:/app/server.log
    env_file:
      - go.env
    depends_on:
      - messages
      - hello

  messages:
    build:
      context: ./messages
      dockerfile: Dockerfile
    volumes:
      - ./messages/messages/server.log:/app/server.log
    env_file:
      - go.env

  hello:
    build:
      context: ./hello
      dockerfile: Dockerfile
    volumes:
      - ./hello/hello/server.log:/app/server.log
    env_file:
      - go.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf