version: '3'

services:
  db:
    image: mysql
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: User
      MYSQL_PASSWORD: 123456789

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dynamic-content:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static-content:/usr/share/nginx/html
    

volumes:
  db_data: