version: '3'

services:

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: 'postgres:16'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketplace

  auth:
    image: 'spring-boot-auth_redis'
    build:
      context: ./auth
    container_name: auth
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_DATABASE=0
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"

  marketplace:
    image: 'spring-boot-marketplace_pg'
    build:
      context: ./marketplace
    container_name: marketplace
    depends_on:
      - postgres
      - auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  front:
    image: 'node-front'
    build:
      context: ./front
    container_name: front
    ports:
      - "3000:3000"
    


