version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server.log:/app/server.log
    env_file:
      - go.env
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  mongo:
    image: mongo
    restart: always
    env_file:
      - mongo.env